name:                orb
version:             0.3.0.0
github:              "flipstone/orb"
license:             MIT
author:              "Flipstone Technology Partners, Inc"
maintainer:          "development@flipstone.com"
copyright:           "2025 Flipstone Technology Partners, Inc"

language: Haskell2010

default-extensions:
  - ImportQualifiedPost

extra-source-files:
  - README.md
  - src/Orb/SwaggerUI/swagger-ui-index.html
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/LICENSE
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/NOTICE
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/favicon-16x16.png
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/favicon-32x32.png
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/index.css
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/index.html
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/oauth2-redirect.html
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-initializer.js
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui-bundle.js
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui-es-bundle-core.js
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui-es-bundle.js
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui-standalone-preset.js
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui.css
  - src/Orb/SwaggerUI/swagger-ui-dist-5.25.2/swagger-ui.js
  

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flipstone/orb#readme>

flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-pretty
  - beeline-params >= 0.1 && < 0.2
  - beeline-routing >= 0.3 && < 0.4
  - bytestring
  - case-insensitive
  - containers
  - dlist
  - file-embed
  - filepath
  - hashable
  - http-media
  - http-types
  - insert-ordered-containers
  - json-fleece-aeson
  - json-fleece-core
  - mtl
  - openapi3
  - optparse-applicative
  - safe-exceptions
  - semialign
  - shrubbery
  - these
  - text
  - unordered-containers
  - wai
  - wai-extra
  - warp

library:
  source-dirs: src
  exposed-modules:
    - Orb
  when:
    - condition: flag(ci)
      then:
        ghc-options:
          - -O2
          - -Wall
          - -Werror
          - -Wcompat
          - -Widentities
          - -Wincomplete-uni-patterns
          - -Wincomplete-patterns
          - -Wincomplete-record-updates
          - -Wmissing-local-signatures
          - -Wmissing-export-lists
          - -Wnoncanonical-monad-instances
          - -Wpartial-fields
          - -Wmissed-specialisations
          - -Wno-implicit-prelude
          - -Wno-safe
          - -Wno-unsafe
          - -fwrite-ide-info -hiedir=.hie
      else:
        ghc-options:
          - -O2
          - -Wall
          - -fwarn-incomplete-uni-patterns
          - -fwarn-incomplete-record-updates

tests:
  orb-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
      - -O2
    dependencies:
      - aeson-pretty
      - beeline-routing
      - file-embed
      - hedgehog
      - orb
      - tasty
      - tasty-golden
      - tasty-hedgehog
